CosmeticsShop/Controllers/SlideManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Tokenizer.Symbols;
using CosmeticsShop.Models;
using DocumentFormat.OpenXml.Office2010.Excel;
using PagedList;

namespace CosmeticsShop.Controllers
{
    public class SlideManageController : Controller
    {
        private ShoppingEntities db = new ShoppingEntities();
        public bool CheckRole(string type)
        {
            Models.User user = Session["User"] as Models.User;
            if (user != null && user.UserType.Name == type)
            {
                return true;
            }
            return false;
        }
        public ActionResult Index(string keyword = "")
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            List<Slide> slides = new List<Slide>();
            if (keyword != "")
            {
                slides = db.Slides.Where(x => x.Name.Contains(keyword)).OrderBy(x => x.ID).ToList();
            }
            else
            {
                slides = db.Slides.Where(x => x.Name.Contains(keyword)).OrderBy(x => x.ID).ToList();
            }
            return View(slides);

           
        }
        public ActionResult ToggleActive(int ID)
        {
            Slide slide = db.Slides.Find(ID);
            slide.Status = !slide.Status;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Create()
        {
            ViewBag.CreatedBy = new SelectList(db.Users, "ID", "Name");
            return View();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Create(Slide slide, HttpPostedFileBase[] ImageUpload)
        {
            for (int i = 0; i < ImageUpload.Length; i++)
            {
                //Check content image
                if (ImageUpload[i] != null && ImageUpload[i].ContentLength > 0)
                {
                    //Get file name
                    var fileName = Path.GetFileName(ImageUpload[i].FileName);
                    //Get path
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    //Check exitst
                    if (!System.IO.File.Exists(path))
                    {
                        //Add image into folder
                        ImageUpload[i].SaveAs(path);
                    }
                }
            }

            if (ImageUpload[0] != null)
            {
                slide.Image = ImageUpload[0].FileName;
            }
            slide.CreatedBy = (Session["User"] as Models.User).ID;
            slide.Status = true;
            slide.CreatedDate = DateTime.Now;
            db.Slides.Add(slide);
            db.SaveChanges();

            ViewBag.Message = "Thêm thành công";
            return View("Details", slide);
        }
        public ActionResult Details(int ID)
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }

            Slide slide = db.Slides.Find(ID);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }
        public ActionResult Edit()
        {
            return RedirectToAction("Index");
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Slide slide, HttpPostedFileBase[] ImageUpload)
        {
            Slide slideUpdate = db.Slides.Find(slide.ID);
            slideUpdate.Name = slide.Name;
            slideUpdate.DisplayOrder = slide.DisplayOrder;
            slideUpdate.Description = slide.Description;

            for (int i = 0; i < ImageUpload.Length; i++)
            {
                //Check content image
                if (ImageUpload[i] != null && ImageUpload[i].ContentLength > 0)
                {
                    //Get file name
                    var fileName = Path.GetFileName(ImageUpload[i].FileName);
                    //Get path
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    //Check exitst
                    if (!System.IO.File.Exists(path))
                    {
                        //Add image into folder
                        ImageUpload[i].SaveAs(path);
                    }
                }
            }

            if (ImageUpload[0] != null)
            {
                slideUpdate.Image = ImageUpload[0].FileName;
            }

            db.SaveChanges();

            ViewBag.Message = "Cập nhật thành công";
            return View("Details", slideUpdate);
        }
        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int? ID)
        {
            Slide slide = db.Slides.Find(ID);
            db.Slides.Remove(slide);
            db.SaveChanges();
            ViewBag.Message = "Xoá thành công";
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CosmeticsShop/Views/SlideManage/Create.cshtml
@model CosmeticsShop.Models.Slide

@{
    ViewBag.Title = "Thêm mới";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Thêm mới</h1>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">      
                <div class="card card-primary">
                    @using (Html.BeginForm("Create", "SlideManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        <div class="card-body">
                            <div class="form-group">
                                <label>Tiêu đề</label>
                                <input type="text" class="form-control" required name="Name">
                            </div>
                            <div class="form-group">
                                <label>Chọn hình (*)</label>
                                <input type="file" class="form-control" name="ImageUpload" required>
                            </div>
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea class="form-control" id="mytextarea" required name="Description"> </textarea>
                            </div>
                            <div class="form-group">
                                <label>Thứ tự bài viết</label>
                                <input type="number" class="form-control" required name="DisplayOrder">
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="/SlideManage/" class="btn btn-light-secondary">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

CosmeticsShop/Views/SlideManage/Delete.cshtml
@model CosmeticsShop.Models.Slide

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Bạn có thật sự muốn xoá?</h3>
<div>

    @using (Html.BeginForm("Delete", "SlideManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <div class="card-footer">
            <a href="/SlideManage/" class="btn btn-light-secondary">Trở lại</a>
            <button type="submit" class="btn btn-danger ml-1">Xoá</button>
        </div>
    }
</div>

CosmeticsShop/Views/SlideManage/Details.cshtml
@model CosmeticsShop.Models.Slide
@{
    ViewBag.Title = @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Xem/Sửa sản phẩm</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Xem/Sửa tin tức</a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="alert alert-primary">
                        <i class="bi bi-star"></i> @Model.Name
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("Edit", "SlideManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        <input type="text" name="ID" value="@Model.ID" hidden />
                        <div class="card-body">
                            <span class="badge bg-success">@ViewBag.Message</span>
                            <div class="form-group">
                                <label>Tên</label>
                                <input type="text" class="form-control" value="@Model.Name" required name="Name">
                            </div>
                            <div class="form-group">
                                <label>Thứ tự bài viết</label>
                                <input type="number" class="form-control" value="@Model.DisplayOrder" required name="DisplayOrder">
                            </div>
                            <div class="form-group">
                                <label>Hình </label>
                                <img src="~/Content/images/@Model.Image" alt="Alternate Text" style="width:25%;height:25%;border: solid 1px gray" />
                            </div>
                            <div class="form-group">
                                <label>Chọn hình mới</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea class="form-control" id="mytextarea" name="Description">@Model.Description</textarea>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <a href="/SlideManage/" class="btn btn-light-secondary">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

CosmeticsShop/Views/SlideManage/Index.cshtml
@model IEnumerable<CosmeticsShop.Models.Slide>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản lý tin tức</h1>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                @if (string.IsNullOrEmpty(Request.Params["keyword"]))
                {
                    <h3 class="card-title">Danh sách tin tức</h3>
                }
                else
                {
                    <h3 class="card-title">Danh sách tin tức với từ khóa "@Request.Params["keyword"]"</h3>
                }
                <div class="card-tools">
                    <form action="/SlideManage/" method="get">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="keyword" class="form-control float-right" placeholder="Tìm kiếm..." required>
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <a href="/SlideManage/Create" class="btn btn-outline-success col-2">Thêm mới</a>
            </div>

            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tiêu đề</th>
                            <th>Người tạo</th>
                            <th>Thứ tự</th>
                            <th>Ngày tạo</th>
                            <th>Trạng thái</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.Name</td>

                                    <td>@item.User.Name</td>
                                    <td>@item.DisplayOrder</td>
                                    <td>@item.CreatedDate</td>
                                    @if (item.Status.Value)
                                    {
                                        <td><span class="badge bg-success">Đã đăng</span></td>
                                    }
                                    else
                                    {
                                        <td><span class="badge bg-danger">Khóa</span></td>
                                    }
                                    <td>
                                        @if (item.Status.Value)
                                        {
                                            <button class="btn btn-outline-danger" onclick="location.href='/SlideManage/ToggleActive/@item.ID'">Khóa</button>
                                        }
                                        else
                                        {
                                            <button class="btn btn-outline-success" onclick="location.href='/SlideManage/ToggleActive/@item.ID'">Mở</button>
                                        }
                                        <button class="btn btn-primary" onclick="location.href='/SlideManage/Details/@item.ID'">Chi tiết/Sửa</button>
                                        <button class="btn btn-danger" onclick="location.href='/SlideManage/Delete/@item.ID'">Xoá</button>
                                    </td>

                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td>
                                    Không tìm thấy sản phẩm...
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>