CosmeticsShop/Controllers/CategoryManageController.cs
using CosmeticsShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsShop.Controllers
{
    public class CategoryManageController : Controller
    {
        ShoppingEntities db = new ShoppingEntities();
        public bool CheckRole(string type)
        {
            Models.User user = Session["User"] as Models.User;
            if (user != null && user.UserType.Name == type)
            {
                return true;
            }
            return false;
        }
        public ActionResult Index(string keyword = "")
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            List<Category> categories = new List<Category>();
            if (keyword != "")
            {
                categories = db.Categories.Where(x => x.Name.Contains(keyword)).ToList();
            }
            else
            {
                categories = db.Categories.Where(x => x.Name.Contains(keyword)).ToList();
            }
            return View(categories);
        }
        public ActionResult ToggleActive(int ID)
        {
            Category category = db.Categories.Find(ID);
            category.IsActive = !category.IsActive;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int ID)
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            Category category = db.Categories.Find(ID);
            return View(category);
        }
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            Category categoryUpdate = db.Categories.Find(category.ID);
            categoryUpdate.Name = category.Name;
            db.SaveChanges();
            ViewBag.Message = "Cập nhật thành công";
            return View("Details", categoryUpdate);
        }
        public ActionResult Edit()
        {
            return RedirectToAction("Index");
        }
        public ActionResult Add()
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            return View();
        }
        [HttpPost]
        public ActionResult Add(Category category)
        {
            category.IsActive = true;
            Category cate = db.Categories.Add(category);
            db.SaveChanges();
            ViewBag.Message = "Thêm thành công";
            return View("Details", cate);
        }
        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int? ID)
        {
            Category category = db.Categories.Find(ID);
            db.Categories.Remove(category);
            db.SaveChanges();
            ViewBag.Message = "Xoá thành công";
            return RedirectToAction("Index");
        }
    }
}

CosmeticsShop/Views/CategoryManage/Add.cshtml
@{
    ViewBag.Title = "Thêm mới danh mục";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Thêm mới</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Thêm mới</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("Add", "CategoryManage", FormMethod.Post))
                {
                    <div class="card-body">
                        <div class="form-group">
                            <label>Tên</label>
                            <input type="text" class="form-control" required name="Name">
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="/CategoryManage/" class="btn btn-light-secondary">Trở lại</a>
                        <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

CosmeticsShop/Views/CategoryManage/Delete.cshtml
@model CosmeticsShop.Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Bạn có thật sự muốn xoá?</h3>
<div>

    @using (Html.BeginForm("Delete", "CategoryManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <div class="card-footer">
            <a href="/CategoryManage/" class="btn btn-light-secondary">Trở lại</a>
            <button type="submit" class="btn btn-danger ml-1">Xoá</button>
        </div>
    }
</div>

CosmeticsShop/Views/CategoryManage/Details.cshtml
@model CosmeticsShop.Models.Category
@{
    ViewBag.Title = @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản lý danh mục</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Xem/Sửa danh mục</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">@Model.Name</h3>
                    </div>
                    @using (Html.BeginForm("Edit", "CategoryManage", FormMethod.Post))
                    {
                        <input type="text" name="ID" value="@Model.ID" hidden />
                        <div class="card-body">
                            <span class="badge bg-success">@ViewBag.Message</span>
                            <div class="form-group">
                                <label>Tên</label>
                                <input type="text" class="form-control" value="@Model.Name" required name="Name">
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <a href="/CategoryManage/" class="btn btn-light-secondary">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

CosmeticsShop/Views/CategoryManage/Index.cshtml
@model List<CosmeticsShop.Models.Category>
@{
    ViewBag.Title = "Danh sách danh mục";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản lý danh mục</h1>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                @if (string.IsNullOrEmpty(Request.Params["keyword"]))
                {
                    <h3 class="card-title">Danh sách danh mục</h3>
                }
                else
                {
                    <h3 class="card-title">Danh sách danh mục với từ khóa "@Request.Params["keyword"]"</h3>
                }
                <div class="card-tools">
                    <form action="/CategoryManage/" method="get">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="keyword" class="form-control float-right" placeholder="Tìm kiếm..." required>
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <a href="/CategoryManage/Add" class="btn btn-outline-success col-2">Thêm mới</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tên</th>
                            <th>Trạng thái</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null && Model.Count > 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.Name</td>
                                    @if (item.IsActive.Value)
                                    {
                                        <td><span class="badge bg-success">Kích hoạt</span></td>
                                    }
                                    else
                                    {
                                        <td><span class="badge bg-danger">Khóa</span></td>
                                    }
                                <td>
                                    @if (item.IsActive.Value)
                                    {
                                        <button class="btn btn-outline-danger" onclick="location.href='/CategoryManage/ToggleActive/@item.ID'">Khóa</button>
                                    }
                                    else
                                    {
                                        <button class="btn btn-outline-success" onclick="location.href='/CategoryManage/ToggleActive/@item.ID'">Mở</button>
                                    }
                                    <button class="btn btn-primary" onclick="location.href='/CategoryManage/Details/@item.ID'">Chi tiết/Sửa</button>
                                    <button class="btn btn-danger" onclick="location.href='/CategoryManage/Delete/@item.ID'">Xoá</button>
                                </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td>
                                    Không tìm thấy sản phẩm...
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>