CosmeticsShop/Controllers/ProductManageController.cs
using CosmeticsShop.Models;
using DocumentFormat.OpenXml.Office2010.Excel;
using PagedList;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CosmeticsShop.Controllers
{
    public class ProductManageController : Controller
    {
        ShoppingEntities db = new ShoppingEntities();
        public bool CheckRole(string type)
        {
            Models.User user = Session["User"] as Models.User;
            if (user != null && user.UserType.Name == type)
            {
                return true;
            }
            return false;
        }
        public ActionResult Index(int CategoryID = 0,  string keyword = "", int? page = 1)
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }

            List<Product> products = new List<Product>();
            if (keyword != "")
            {
                products = db.Products.Where(x => x.Name.Contains(keyword)).OrderBy(x => x.ID).ToList();
            }
            if (CategoryID != 0)
            {
                ViewBag.NamePage = "Category " + db.Categories.Find(CategoryID).Name;
                ViewBag.ListProduct = db.Products.Where(x => x.IsActive == true && x.CategoryID == CategoryID).ToList();
            }
            else
            {
                products = db.Products.Where(x => x.Name.Contains(keyword)).OrderBy(x => x.ID).ToList();
            }
            //Phân trang
            if (page == null) page = 1;
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            PagedList<Product> models = new PagedList<Product>(products.AsQueryable(), pageNumber, pageSize);

            //Trang hiện tại
            ViewBag.CurrentPage = pageNumber;
            return View(models);

        }
        public ActionResult ToggleActive(int ID)
        {
            Product product = db.Products.Find(ID);
            product.IsActive = !product.IsActive;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(int ID)
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            Product product = db.Products.Find(ID);
            ViewBag.CategoryList = db.Categories.ToList();
            return View(product);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(Product product, HttpPostedFileBase[] ImageUpload)
        {
            Product productUpdate = db.Products.Find(product.ID);
            productUpdate.Name = product.Name;
            productUpdate.Price = product.Price;
            productUpdate.Quantity = product.Quantity;
            productUpdate.Type = product.Type;
            productUpdate.CategoryID = product.CategoryID;
            productUpdate.Description = product.Description;

            for (int i = 0; i < ImageUpload.Length; i++)
            {
                //Check content image
                if (ImageUpload[i] != null && ImageUpload[i].ContentLength > 0)
                {
                    //Get file name
                    var fileName = Path.GetFileName(ImageUpload[i].FileName);
                    //Get path
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    //Check exitst
                    if (!System.IO.File.Exists(path))
                    {
                        //Add image into folder
                        ImageUpload[i].SaveAs(path);
                    }
                }
            }

            if (ImageUpload[0] != null)
            {
                productUpdate.Image1 = ImageUpload[0].FileName;
            }
            if (ImageUpload[1] != null)
            {
                productUpdate.Image2 = ImageUpload[1].FileName;
            }
            if (ImageUpload[2] != null)
            {
                productUpdate.Image3 = ImageUpload[2].FileName;
            }
            db.SaveChanges();

            ViewBag.CategoryList = db.Categories.ToList();
            ViewBag.Message = "Cập nhật thành công";
            return View("Details", productUpdate);
        }
        public ActionResult Edit()
        {
            return RedirectToAction("Index");
        }
        public ActionResult Add()
        {
            if (CheckRole("Admin"))
            {

            }
            else
            {
                return RedirectToAction("Index", "Admin");
            }
            ViewBag.CategoryList = db.Categories.Where(x => x.IsActive == true).ToList();
            return View();
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Add(Product product, HttpPostedFileBase[] ImageUpload)
        {
            for (int i = 0; i < ImageUpload.Length; i++)
            {
                //Check content image
                if (ImageUpload[i] != null && ImageUpload[i].ContentLength > 0)
                {
                    //Get file name
                    var fileName = Path.GetFileName(ImageUpload[i].FileName);
                    //Get path
                    var path = Path.Combine(Server.MapPath("~/Content/images"), fileName);
                    //Check exitst
                    if (!System.IO.File.Exists(path))
                    {
                        //Add image into folder
                        ImageUpload[i].SaveAs(path);
                    }
                }
            }

            if (ImageUpload[0] != null)
            {
                product.Image1 = ImageUpload[0].FileName;
            }
            if (ImageUpload[1] != null)
            {
                product.Image2 = ImageUpload[1].FileName;
            }
            if (ImageUpload[2] != null)
            {
                product.Image3 = ImageUpload[2].FileName;
            }
            product.CreatedBy = (Session["User"] as Models.User).ID;
            product.ViewCount = 0;
            product.PurchasedCount = 0;
            product.IsActive = true;
            db.Products.Add(product);
            db.SaveChanges();

            ViewBag.CategoryList = db.Categories.Where(x => x.IsActive == true).ToList();
            ViewBag.Message = "Thêm thành công";
            return View("Details", product);
        }
       
        public ActionResult Delete()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Delete(int? ID)
        {
            Product product = db.Products.Find(ID);
            db.Products.Remove(product);
            db.SaveChanges();
            ViewBag.Message = "Xoá thành công";
            return RedirectToAction("Index");
        }
    }
}

CosmeticsShop/Views/ProductManage/Add.cshtml
@{
    ViewBag.Title = "Thêm mới";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    List<CosmeticsShop.Models.Category> categoryies = ViewBag.CategoryList as List<CosmeticsShop.Models.Category>;
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Thêm mới</h1>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("Add", "ProductManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        <div class="card-body">
                            <div class="form-group">
                                <label>Tên</label>
                                <input type="text" class="form-control" required name="Name">
                            </div>
                            <div class="form-group">
                                <label>Danh mục</label>
                                <select name="CategoryID" class="form-control">
                                    @foreach (var item in categoryies)
                                    {
                                        <option value="@item.ID">@item.Name</option>
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Đơn giá</label>
                                <input type="text" class="form-control" required name="Price">
                            </div>
                            <div class="form-group">
                                <label>Phù hợp cho (Da dầu / Da khô / Da hỗn hợp / Da dễ bị kích ứng)</label>
                                <input type="text" class="form-control" required name="Type">
                            </div>
                            <div class="form-group">
                                <label>Số lượng</label>
                                <input type="text" class="form-control" required name="Quantity">
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 1 (*)</label>
                                <input type="file" class="form-control" name="ImageUpload" required>
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 2</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 3</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea class="form-control" id="mytextarea" required name="Description"> </textarea>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <a href="/ProductManage/" class="btn btn-default">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

CosmeticsShop/Views/ProductManage/Delete.cshtml
@model CosmeticsShop.Models.Product

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Bạn có thật sự muốn xoá?</h1>
<div>

    @using (Html.BeginForm("Delete", "ProductManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
    {
        <div class="card-footer">
            <a href="/ProductManage/"  class="btn btn-light-secondary">Trở lại</a>
            <button type="submit" class="btn btn-danger ml-1">Xoá</button>
        </div>
    }
</div>

CosmeticsShop/Views/ProductManage/Details.cshtml
@model CosmeticsShop.Models.Product
@{
    ViewBag.Title = @Model.Name;
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    List<CosmeticsShop.Models.Category> categories = ViewBag.CategoryList as List<CosmeticsShop.Models.Category>;
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Xem/Sửa sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Xem/Sửa sản phẩm</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="alert alert-primary">
                        <i class="bi bi-star"></i> @Model.Name
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    @using (Html.BeginForm("Edit", "ProductManage", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        <input type="text" name="ID" value="@Model.ID" hidden />
                        <div class="card-body">
                            <span class="badge bg-success">@ViewBag.Message</span>
                            <div class="form-group">
                                <label>Tên</label>
                                <input type="text" class="form-control" value="@Model.Name" required name="Name">
                            </div>
                            <div class="form-group">
                                <label>Danh mục</label>
                                <select name="CategoryID" class="form-control">
                                    @foreach (var item in categories)
                                    {
                                        if (item.ID == Model.CategoryID)
                                        {
                                            <option value="@item.ID" selected>@item.Name</option>
                                        }
                                        else
                                        {
                                            <option value="@item.ID">@item.Name</option>
                                        }
                                    }
                                </select>
                            </div>
                            <div class="form-group">
                                <label>Đơn giá</label>
                                <input type="text" class="form-control" value="@Model.Price.Value" required name="Price">
                            </div>
                            <div class="form-group">
                                <label>Số lượng</label>
                                <input type="text" class="form-control" value="@Model.Quantity" required name="Quantity">
                            </div>
                            <div class="form-group">
                                <label>Phù hợp với: </label>
                                <input type="text" class="form-control" value="@Model.Type" required name="Type">
                            </div>
                            <div class="form-group">
                                <label>Lượt xem</label>
                                <input type="text" class="form-control" value="@Model.ViewCount" required name="ViewCount" disabled>
                            </div>
                            <div class="form-group">
                                <label>Đã bán</label>
                                <input type="text" class="form-control" value="@Model.PurchasedCount" required name="PurchasedCount" disabled>
                            </div>
                            <div class="form-group">
                                <label>Hình 1</label>
                                <img src="~/Content/images/@Model.Image1" alt="Alternate Text" style="width:15%;height:15%;border: solid 1px gray" />
                                <label>Hình 2</label>
                                <img src="~/Content/images/@Model.Image2" alt="Alternate Text" style="width:15%;height:15%;border: solid 1px gray" />
                                <label>Hình 3</label>
                                <img src="~/Content/images/@Model.Image3" alt="Alternate Text" style="width:15%;height:15%;border: solid 1px gray" />
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 1 mới</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 2 mới</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            <div class="form-group">
                                <label>Chọn hình 3 mới</label>
                                <input type="file" class="form-control" name="ImageUpload">
                            </div>
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea class="form-control" required id="mytextarea"  name="Description">@Model.Description</textarea>
                            </div>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <a href="/ProductManage/" class="btn btn-light-secondary">Trở lại</a>
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>

CosmeticsShop/Views/ProductManage/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<CosmeticsShop.Models.Product>
@{
    ViewBag.Title = "Danh sách sản phẩm";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Quản lý sản phẩm</h1>
            </div>
        </div>
    </div>
</div>
<!-- /.content-header -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                @if (string.IsNullOrEmpty(Request.Params["keyword"]))
                {
                    <h3 class="card-title">Danh sách sản phẩm: Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount</h3>
                }
                else
                {
                    <h3 class="card-title">Danh sách sản phẩm với từ khóa "@Request.Params["keyword"]"</h3>
                }
                <div class="card-tools">
                    <form action="/ProductManage/" method="get">
                        <div class="input-group input-group-sm" style="width: 150px;">
                            <input type="text" name="keyword" class="form-control float-right" placeholder="Tìm kiếm...">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-default">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="card-body">
                <a href="/ProductManage/Add" class="btn btn-outline-success col-2">Thêm mới</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Tên</th>
                            <th>Hình ảnh</th>
                            <th>Người tạo</th>
                            <th>Đơn giá</th>
                            <th>Trạng thái</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.Name</td>
                                    <td><img src="~/Content/images/@item.Image1" alt="Alternate Text" style="width:50px;height:80px" /></td>
                                    <td>@item.User.Name</td>
                                    <td>@item.Price.Value.ToString("#,##")₫</td>
                                    @if (item.IsActive.Value)
                                    {
                                        <td><span class="badge bg-success">Kích hoạt</span></td>
                                    }
                                    else
                                    {
                                        <td><span class="badge bg-danger">Khóa</span></td>
                                    }
                                    <td>
                                        @if (item.IsActive.Value)
                                        {
                                            <button class="btn btn-outline-danger" onclick="location.href='/ProductManage/ToggleActive/@item.ID'">Khóa</button>
                                        }
                                        else
                                        {
                                            <button class="btn btn-outline-success" onclick="location.href='/ProductManage/ToggleActive/@item.ID'">Mở</button>
                                        }
                                        <button class="btn btn-primary" onclick="location.href='/ProductManage/Details/@item.ID'">Chi tiết/Sửa</button>
                                        <button class="btn btn-danger" onclick="location.href='/ProductManage/Delete/@item.ID'">
                                            Xoá
                                        </button>
                                    </td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td>
                                    Không tìm thấy sản phẩm...
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <!-- Thêm mã phân trang -->
                <div class="card-body">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination pagination-primary justify-content-center">
                            <li class="page-item">
                                <a class="page-link" href="#">
                                    <span aria-hidden="true"><i class="bi bi-chevron-left"></i></span>
                                </a>
                            </li>
                            <li class="page-item">
                                @Html.PagedListPager(Model, page => Url.Action("Index",
                              new { page }))

                            </li>

                            <li class="page-item">
                                <a class="page-link" href="#">
                                    <span aria-hidden="true"><i class="bi bi-chevron-right"></i></span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>

                <!-- Kết thúc -->
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>